Refactor: From JVM to Native using Quarkus
okp4/kafka-processor-cosmos-block pull request #25
Opened 2022-06-13 15:18 UTC by ingvaar

> This is a complete project refactor.

The logic stays the same, the tests are not impacted.

Instead of the JVM, we new use native executable thanks to [Quarkus](https://quarkus.io).

Parts of the project that got updated:
- Dockerfile : now build a complete image running the project natively
- Topology creation: now uses [Quarkus Kafka Streams](https://quarkus.io/guides/kafka-streams)
- README: updated to reflect the use of Quarkus
- Github workflows: update of the Docker build part

2022-06-14 12:39 UTC, amimart requested changes
Thanks for such refactoring, native build will bring some significant lightness.

I won't go in detailed remarks for the moment, but here a general thought, I saw the maven publish tasks was removed, but I'd like to keep the Maven publication. From my point of view the quarkus native build should be seen as an option, but not incompatible with standard jar delivery. Regarding the CI we could have different build / publish jobs for jar / native builds.

2022-06-15 09:50 UTC, amimart requested changes
Great! I just have some minor remarks, opened to discussion 😉

2022-06-15 09:50 UTC, amimart commented on .github/workflows/build.yml
> +  build-native:
As we already cover this build type in the docker build, maybe we can avoid it.

2022-06-15 09:50 UTC, amimart commented on .github/workflows/build.yml
> +          java-version: '11'
I don't think java is needed as we build in docker.

2022-06-15 09:50 UTC, amimart commented on .github/workflows/build.yml
> +          java-version: '11'
I don't think java is needed as we build in docker.

2022-06-15 09:50 UTC, amimart commented on Dockerfile
> +RUN ./gradlew build -Dquarkus.package.type=native --no-daemon
We can bypass the test task here, it is already covered by the Test workflow.

```suggestion
RUN ./gradlew build -x check -Dquarkus.package.type=native --no-daemon
```

2022-06-15 09:50 UTC, amimart commented on Dockerfile
> +RUN ./gradlew build -Dquarkus.package.type=native --no-daemon
We can bypass the test task here, it is already covered by the Test workflow.

```suggestion
RUN ./gradlew build -x check -Dquarkus.package.type=native --no-daemon
```

2022-06-15 09:50 UTC, amimart commented on build.gradle.kts
> +    mavenLocal()
We do not need the local maven repository.

```suggestion
```

2022-06-15 09:50 UTC, amimart commented on build.gradle.kts
> +    mavenLocal()
We do not need the local maven repository.

```suggestion
```

2022-06-15 09:50 UTC, amimart commented on settings.gradle.kts
> +        mavenLocal()
We do not need the local maven repository.

2022-06-15 09:50 UTC, amimart commented on settings.gradle.kts
> +        mavenLocal()
We do not need the local maven repository.

2022-06-15 14:08 UTC, amimart submitted a review, later dismissed
Looks good to me! Thank you 😉

2022-06-15 14:57 UTC, ccamel commented on src/test/kotlin/com/okp4/processor/cosmos/TopologyTest.kt
> +        topologyProducer.topicError = "error"
Just to have something to say! 😁

```suggestion
        val topologyProducer = TopologyProducer().apply {
            topicIn = "in"
            topicOut = "out"
            topicError = "error"
        }
```

2022-06-15 15:05 UTC, amimart approved these changes

2022-06-15 15:12 UTC, ccamel approved these changes
Go! 🚀

2022-06-15 15:31 UTC, merged